export enum RoomType {
    LIVING_ROOM = "LIVING_ROOM",
    BEDROOM = "BEDROOM",
    KITCHEN = "KITCHEN",
    BATHROOM = "BATHROOM",
    HALLWAY = "HALLWAY",
    BALCONY = "BALCONY",
    TERRACE = "TERRACE",
    BASEMENT = "BASEMENT",
    STORAGE = "STORAGE",
    OFFICE = "OFFICE",
    DINING_ROOM = "DINING_ROOM",
    OTHER = "OTHER"
}